"""Add revenue field to FactCampaignPerformance

Revision ID: 4b9a0687c66d
Revises: a51a4240c897
Create Date: 2025-05-05 18:39:24.171771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b9a0687c66d'
down_revision = 'a51a4240c897'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Only add the revenue column to fact_campaign_performance
    op.add_column('fact_campaign_performance', sa.Column('revenue', sa.DECIMAL(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fact_campaign_performance', 'revenue')
    # ### end Alembic commands ###
