"""Create Data Vault integration models

Revision ID: 90061cb27c9c
Revises: 
Create Date: 2025-05-02 15:40:36.392192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90061cb27c9c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_ad_groups',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dim_branches',
    sa.Column('branch_key', sa.Integer(), nullable=False),
    sa.Column('branch_hk', sa.String(length=32), nullable=False),
    sa.Column('branch_code', sa.String(length=20), nullable=False),
    sa.Column('branch_name', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('branch_type', sa.String(length=30), nullable=True),
    sa.Column('channel_category', sa.String(length=30), nullable=True),
    sa.Column('active_flag', sa.String(length=1), nullable=True),
    sa.Column('last_updated_dts', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('branch_key'),
    sa.UniqueConstraint('branch_hk')
    )
    op.create_table('dim_campaign_templates',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dim_channels',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('EMAIL', 'SMS', 'APP', 'WEB', 'SOCIAL', name='channeltype'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dim_data_sources',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dim_dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_weekend', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('dim_kpis',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dim_merchants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_hk', sa.String(length=32), nullable=False),
    sa.Column('merchant_name', sa.String(length=100), nullable=True),
    sa.Column('merchant_category', sa.String(length=50), nullable=True),
    sa.Column('merchant_location', sa.String(length=100), nullable=True),
    sa.Column('merchant_country', sa.String(length=50), nullable=True),
    sa.Column('last_updated_dts', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_hk')
    )
    op.create_table('dim_products',
    sa.Column('product_key', sa.Integer(), nullable=False),
    sa.Column('product_hk', sa.String(length=32), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('product_type', sa.String(length=30), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('principal_amt', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('interest_rate_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reward_program', sa.String(length=50), nullable=True),
    sa.Column('tenure_months', sa.Integer(), nullable=True),
    sa.Column('property_type', sa.String(length=50), nullable=True),
    sa.Column('last_updated_dts', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('product_key'),
    sa.UniqueConstraint('product_hk')
    )
    op.create_table('dim_segments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('resource', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('oauth_provider', sa.String(length=20), nullable=True),
    sa.Column('oauth_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('ad_group_role_mappings',
    sa.Column('ad_group_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['ad_group_id'], ['dim_ad_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ad_group_id', 'role_id')
    )
    op.create_table('dim_campaigns',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('segment_id', sa.BigInteger(), nullable=True),
    sa.Column('template_id', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['segment_id'], ['dim_segments.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['dim_campaign_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dim_customers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('income_bracket', sa.String(length=50), nullable=True),
    sa.Column('risk_profile', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('joined_date', sa.Date(), nullable=True),
    sa.Column('active_product_count', sa.Integer(), nullable=True),
    sa.Column('latest_segment_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['latest_segment_id'], ['dim_segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fact_data_ingestion_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('run_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['dim_data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fact_segment_performance',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('segment_id', sa.BigInteger(), nullable=False),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('engagement_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['date_key'], ['dim_dates.id'], ),
    sa.ForeignKeyConstraint(['segment_id'], ['dim_segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fact_user_actions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('dim_contact_preferences',
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('do_not_email', sa.Boolean(), nullable=True),
    sa.Column('do_not_sms', sa.Boolean(), nullable=True),
    sa.Column('preferred_contact_time', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['dim_customers.id'], ),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('dim_customer_ai_features',
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('churn_risk_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('lifetime_value_score', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('propensity_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('scored_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['dim_customers.id'], ),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('fact_campaign_kpi_results',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.Column('kpi_id', sa.BigInteger(), nullable=False),
    sa.Column('value', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['dim_campaigns.id'], ),
    sa.ForeignKeyConstraint(['kpi_id'], ['dim_kpis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fact_campaign_performance',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('segment_id', sa.BigInteger(), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('impressions', sa.BigInteger(), nullable=True),
    sa.Column('clicks', sa.BigInteger(), nullable=True),
    sa.Column('conversions', sa.BigInteger(), nullable=True),
    sa.Column('spend', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['dim_campaigns.id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['dim_channels.id'], ),
    sa.ForeignKeyConstraint(['date_key'], ['dim_dates.id'], ),
    sa.ForeignKeyConstraint(['segment_id'], ['dim_segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fact_channel_performance',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=True),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('impressions', sa.BigInteger(), nullable=True),
    sa.Column('clicks', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['dim_campaigns.id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['dim_channels.id'], ),
    sa.ForeignKeyConstraint(['date_key'], ['dim_dates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fact_customer_channel_activity',
    sa.Column('activity_key', sa.Integer(), nullable=False),
    sa.Column('customer_key', sa.Integer(), nullable=False),
    sa.Column('date_key', sa.Integer(), nullable=False),
    sa.Column('channel_key', sa.Integer(), nullable=False),
    sa.Column('opens', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('logins', sa.Integer(), nullable=True),
    sa.Column('session_count', sa.Integer(), nullable=True),
    sa.Column('session_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('conversion_count', sa.Integer(), nullable=True),
    sa.Column('bounce_count', sa.Integer(), nullable=True),
    sa.Column('activity_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('load_dts', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['channel_key'], ['dim_channels.id'], ),
    sa.ForeignKeyConstraint(['customer_key'], ['dim_customers.id'], ),
    sa.ForeignKeyConstraint(['date_key'], ['dim_dates.id'], ),
    sa.PrimaryKeyConstraint('activity_key'),
    sqlite_autoincrement=True
    )
    op.create_table('fact_feedback',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=True),
    sa.Column('rating', sa.SmallInteger(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['dim_campaigns.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['dim_customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fact_repayments',
    sa.Column('repayment_key', sa.Integer(), nullable=False),
    sa.Column('repayment_id', sa.String(length=32), nullable=False),
    sa.Column('customer_key', sa.Integer(), nullable=False),
    sa.Column('product_key', sa.Integer(), nullable=False),
    sa.Column('date_key', sa.Integer(), nullable=False),
    sa.Column('repayment_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('principal_component', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('interest_component', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('fee_component', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('remaining_principal', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('payment_method', sa.String(length=30), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.Column('days_past_due', sa.Integer(), nullable=True),
    sa.Column('repayment_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('load_dts', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_key'], ['dim_customers.id'], ),
    sa.ForeignKeyConstraint(['date_key'], ['dim_dates.id'], ),
    sa.ForeignKeyConstraint(['product_key'], ['dim_products.product_key'], ),
    sa.PrimaryKeyConstraint('repayment_key'),
    sa.UniqueConstraint('repayment_id')
    )
    op.create_table('fact_spend_cc',
    sa.Column('spend_txn_key', sa.Integer(), nullable=False),
    sa.Column('txn_hk', sa.String(length=32), nullable=False),
    sa.Column('customer_key', sa.Integer(), nullable=False),
    sa.Column('product_key', sa.Integer(), nullable=False),
    sa.Column('date_key', sa.Integer(), nullable=False),
    sa.Column('merchant_key', sa.Integer(), nullable=True),
    sa.Column('txn_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('txn_currency', sa.String(length=3), nullable=True),
    sa.Column('rewards_earned', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('interest_charged', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('available_credit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('reward_program', sa.String(length=50), nullable=True),
    sa.Column('txn_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('load_dts', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_key'], ['dim_customers.id'], ),
    sa.ForeignKeyConstraint(['date_key'], ['dim_dates.id'], ),
    sa.ForeignKeyConstraint(['merchant_key'], ['dim_merchants.id'], ),
    sa.ForeignKeyConstraint(['product_key'], ['dim_products.product_key'], ),
    sa.PrimaryKeyConstraint('spend_txn_key'),
    sa.UniqueConstraint('txn_hk')
    )
    op.create_table('fact_transactions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=True),
    sa.Column('product_key', sa.Integer(), nullable=True),
    sa.Column('txn_amount', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('txn_type', sa.String(length=50), nullable=True),
    sa.Column('campaign_id', sa.BigInteger(), nullable=True),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['dim_campaigns.id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['dim_channels.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['dim_customers.id'], ),
    sa.ForeignKeyConstraint(['product_key'], ['dim_products.product_key'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fact_transactions_datavault',
    sa.Column('transaction_key', sa.Integer(), nullable=False),
    sa.Column('txn_hk', sa.String(length=32), nullable=False),
    sa.Column('customer_key', sa.Integer(), nullable=False),
    sa.Column('product_key', sa.Integer(), nullable=False),
    sa.Column('date_key', sa.Integer(), nullable=False),
    sa.Column('branch_key', sa.Integer(), nullable=True),
    sa.Column('txn_type', sa.String(length=30), nullable=True),
    sa.Column('txn_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('txn_currency', sa.String(length=3), nullable=True),
    sa.Column('merchant_category', sa.String(length=50), nullable=True),
    sa.Column('txn_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('load_dts', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['branch_key'], ['dim_branches.branch_key'], ),
    sa.ForeignKeyConstraint(['customer_key'], ['dim_customers.id'], ),
    sa.ForeignKeyConstraint(['date_key'], ['dim_dates.id'], ),
    sa.ForeignKeyConstraint(['product_key'], ['dim_products.product_key'], ),
    sa.PrimaryKeyConstraint('transaction_key'),
    sa.UniqueConstraint('txn_hk')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fact_transactions_datavault')
    op.drop_table('fact_transactions')
    op.drop_table('fact_spend_cc')
    op.drop_table('fact_repayments')
    op.drop_table('fact_feedback')
    op.drop_table('fact_customer_channel_activity')
    op.drop_table('fact_channel_performance')
    op.drop_table('fact_campaign_performance')
    op.drop_table('fact_campaign_kpi_results')
    op.drop_table('dim_customer_ai_features')
    op.drop_table('dim_contact_preferences')
    op.drop_table('user_roles')
    op.drop_table('role_permissions')
    op.drop_table('fact_user_actions')
    op.drop_table('fact_segment_performance')
    op.drop_table('fact_data_ingestion_runs')
    op.drop_table('dim_customers')
    op.drop_table('dim_campaigns')
    op.drop_table('ad_group_role_mappings')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_table('dim_segments')
    op.drop_table('dim_products')
    op.drop_table('dim_merchants')
    op.drop_table('dim_kpis')
    op.drop_table('dim_dates')
    op.drop_table('dim_data_sources')
    op.drop_table('dim_channels')
    op.drop_table('dim_campaign_templates')
    op.drop_table('dim_branches')
    op.drop_table('dim_ad_groups')
    # ### end Alembic commands ###
