"""Add retention_rate to FactSegmentPerformance

Revision ID: a51a4240c897
Revises: 90061cb27c9c
Create Date: 2025-05-05 18:34:49.734759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a51a4240c897'
down_revision = '90061cb27c9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Only add the retention_rate column to fact_segment_performance
    op.add_column('fact_segment_performance', sa.Column('retention_rate', sa.DECIMAL(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fact_segment_performance', 'retention_rate')
    # ### end Alembic commands ###
